# BINARY LOGISTIC REGRESSION WITH HYPERPARAMETER TUNING

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
# create dataset
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

In [4]:
df = pd.DataFrame(X)
df, y

(            0         1         2         3         4         5         6  \
 0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
 1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
 2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
 3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
 4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
 ..        ...       ...       ...       ...       ...       ...       ...   
 995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
 996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
 997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
 998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
 999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   
 
             7         8         9  
 0   -1.210161 -0.628077 

In [5]:
# trai n test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
y_test

array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

# MODEL TRAINING

In [6]:
from sklearn.linear_model import LogisticRegression
bin_logi_reg_model = LogisticRegression()

In [7]:
bin_logi_reg_model.fit(x_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [8]:
y_pred = bin_logi_reg_model.predict(x_test)

In [9]:
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [10]:
y_prob = bin_logi_reg_model.predict_proba(x_test)

In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [13]:
accuracy_score = accuracy_score(y_test,y_pred)
accuracy_score

0.8466666666666667

In [14]:
confusion_matrix = confusion_matrix(y_test,y_pred)
confusion_matrix

array([[118,  17],
       [ 29, 136]])

In [53]:
classification_report = classification_report(y_test,y_pred, output_dict=True)
classification_report

{'0': {'precision': 0.7898089171974523,
  'recall': 0.9185185185185185,
  'f1-score': 0.8493150684931506,
  'support': 135.0},
 '1': {'precision': 0.9230769230769231,
  'recall': 0.8,
  'f1-score': 0.8571428571428571,
  'support': 165.0},
 'accuracy': 0.8533333333333334,
 'macro avg': {'precision': 0.8564429201371877,
  'recall': 0.8592592592592593,
  'f1-score': 0.8532289628180039,
  'support': 300.0},
 'weighted avg': {'precision': 0.8631063204311613,
  'recall': 0.8533333333333334,
  'f1-score': 0.8536203522504893,
  'support': 300.0}}

# HYPERPARAMETER TUNING

### 1)GRID SEARCH HYPERPARAMETER TUNING

In [41]:
model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c = [100,10,1.0,0.1,0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [42]:
params = dict(penalty=penalty, C=c, solver=solver,)
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']}

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold

In [44]:
cv = StratifiedKFold(n_splits=5, shuffle=False)
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [45]:
grid

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [46]:
grid.fit(x_train, y_train)

/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/aj/miniconda3/envs/

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [47]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}

In [48]:
grid.best_score_

np.float64(0.8785714285714287)

In [49]:
y_pred = grid.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [57]:
accuracy_score = accuracy_score(y_test,y_pred)
accuracy_score

0.8533333333333334

In [58]:
confusion_matrix = confusion_matrix(y_test,y_pred)
confusion_matrix

array([[124,  11],
       [ 33, 132]])

In [59]:
classification_report = classification_report(y_test,y_pred, output_dict=True)
classification_report

{'0': {'precision': 0.7898089171974523,
  'recall': 0.9185185185185185,
  'f1-score': 0.8493150684931506,
  'support': 135.0},
 '1': {'precision': 0.9230769230769231,
  'recall': 0.8,
  'f1-score': 0.8571428571428571,
  'support': 165.0},
 'accuracy': 0.8533333333333334,
 'macro avg': {'precision': 0.8564429201371877,
  'recall': 0.8592592592592593,
  'f1-score': 0.8532289628180039,
  'support': 300.0},
 'weighted avg': {'precision': 0.8631063204311613,
  'recall': 0.8533333333333334,
  'f1-score': 0.8536203522504893,
  'support': 300.0}}

### 2)RANDOMISED SEARCH CV

In [60]:
from sklearn.model_selection import RandomizedSearchCV

In [61]:
model = LogisticRegression()
random_cv = RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, scoring='accuracy')

In [63]:
random_cv.fit(x_train,y_train)

/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:516: FitFailedWarning: 
15 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/aj/miniconda3/envs/genai/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py", line 1218, in f

,estimator,LogisticRegression()
,param_distributions,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['newton-cg', 'lbfgs', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [64]:
random_cv.best_score_

np.float64(0.8785714285714287)

In [65]:
random_cv.best_params_

{'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.01}

In [66]:
y_pred = random_cv.predict(x_test)
y_pred


array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0])

In [68]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score = accuracy_score(y_test,y_pred)
accuracy_score

0.8533333333333334

In [69]:
confusion_matrix = confusion_matrix(y_test,y_pred)
confusion_matrix

array([[124,  11],
       [ 33, 132]])

In [70]:
classification_report = classification_report(y_test,y_pred, output_dict=True)
classification_report

{'0': {'precision': 0.7898089171974523,
  'recall': 0.9185185185185185,
  'f1-score': 0.8493150684931506,
  'support': 135.0},
 '1': {'precision': 0.9230769230769231,
  'recall': 0.8,
  'f1-score': 0.8571428571428571,
  'support': 165.0},
 'accuracy': 0.8533333333333334,
 'macro avg': {'precision': 0.8564429201371877,
  'recall': 0.8592592592592593,
  'f1-score': 0.8532289628180039,
  'support': 300.0},
 'weighted avg': {'precision': 0.8631063204311613,
  'recall': 0.8533333333333334,
  'f1-score': 0.8536203522504893,
  'support': 300.0}}